### ISSUE TITLE
你这直接拿了人家egg-init的代码就自己开源了？

### ISSUE THREAD

**Issue by miaoihan** [unclexiao/create-tell#4]
一行代码也没改

**Comment by unclexiao** [comment]
是的，这是一个自己使用的脚手架工具，用于生成模板。

比如`lib/boilerplates.js` 这里定义了写好的[egg-boilerplate-mp](https://github.com/unclexiao/egg-boilerplate-mp/tree/master/boilerplate)，发布到[npm仓库](https://www.npmjs.com/package/create-tell)之后，就可以一个命令创建新项目了。

官方的[egg-init](https://github.com/eggjs/egg-init)命令，就只有simple和plugin模板，我现在自己定制了3个模板，没问题吧？

Egg的定位不就是框架的框架么？
